# Generated by Django 5.2 on 2025-04-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('next_gen_sms', '0002_attendance_teacher'),
    ]

    operations = [
    ]
