# Generated by Django 5.2 on 2025-04-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_gen_sms', '0003_populate_attendance_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='achievements',
            field=models.TextField(blank=True, help_text='Enter achievements separated by newlines', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activities',
            field=models.TextField(blank=True, help_text='Enter recent activities separated by newlines', null=True),
        ),
    ]
