# Generated by Django 5.2 on 2025-04-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_gen_sms', '0004_userprofile_achievements_userprofile_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
    ]
