# Generated by Django 5.2 on 2025-04-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('next_gen_sms', '0008_exam_examresult'),
    ]

    operations = [
    ]
